#!/bin/bash
# ==============================================================================
# Script Name: sysctl_harden.sh
# Description: Comprehensive kernel hardening via sysctl parameters
#              Hardens network stack, memory, and kernel security settings
# Author: CCDC Team
# Date: 2025-2026
# Version: 1.0
#
# Usage:
#   ./sysctl_harden.sh [options]
#
# Options:
#   -h, --help       Show this help message
#   -r, --revert     Revert to backup settings
#   -s, --show       Show current security-relevant settings
#   -n, --no-backup  Skip creating backup
#   -q, --quiet      Minimal output
#
# Supported Systems:
#   - Ubuntu 20.04+
#   - Fedora 38+
#   - Rocky/Alma/Oracle Linux 8+
#   - Debian 11+
#
# What This Script Does:
#   - Disables IP forwarding (unless router)
#   - Enables SYN cookies (SYN flood protection)
#   - Disables ICMP redirects (MITM prevention)
#   - Enables reverse path filtering (anti-spoofing)
#   - Disables source routing
#   - Hardens IPv6 settings
#   - Enables ASLR and memory protections
#   - Restricts kernel pointer exposure
#   - Enables dmesg restriction
#   - Disables magic SysRq key
#   - Protects symlinks and hardlinks
#
# Exit Codes:
#   0 - Success
#   1 - Error
#   3 - Permission denied
#
# ==============================================================================

set -uo pipefail

# --- Configuration ---
SCRIPT_NAME="$(basename "$0")"
SYSCTL_FILE="/etc/sysctl.d/99-ccdc-hardening.conf"
BACKUP_FILE="/etc/sysctl.d/99-ccdc-hardening.conf.backup"
QUIET=false
NO_BACKUP=false

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# --- Helper Functions ---
usage() {
    head -40 "$0" | grep -E "^#" | sed 's/^# //' | sed 's/^#//'
    exit 0
}

log() {
    [[ "$QUIET" == "false" ]] && echo -e "${GREEN}[INFO]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root"
        exit 3
    fi
}

# --- Show current settings ---
show_settings() {
    echo "=========================================="
    echo "CURRENT SECURITY-RELEVANT SYSCTL SETTINGS"
    echo "=========================================="
    echo ""

    echo "--- Network Security ---"
    sysctl net.ipv4.ip_forward 2>/dev/null
    sysctl net.ipv4.conf.all.accept_redirects 2>/dev/null
    sysctl net.ipv4.conf.all.send_redirects 2>/dev/null
    sysctl net.ipv4.conf.all.accept_source_route 2>/dev/null
    sysctl net.ipv4.conf.all.rp_filter 2>/dev/null
    sysctl net.ipv4.tcp_syncookies 2>/dev/null
    sysctl net.ipv4.icmp_echo_ignore_broadcasts 2>/dev/null
    echo ""

    echo "--- IPv6 Security ---"
    sysctl net.ipv6.conf.all.accept_redirects 2>/dev/null
    sysctl net.ipv6.conf.all.accept_source_route 2>/dev/null
    sysctl net.ipv6.conf.all.accept_ra 2>/dev/null
    echo ""

    echo "--- Kernel Security ---"
    sysctl kernel.randomize_va_space 2>/dev/null
    sysctl kernel.kptr_restrict 2>/dev/null
    sysctl kernel.dmesg_restrict 2>/dev/null
    sysctl kernel.sysrq 2>/dev/null
    sysctl kernel.yama.ptrace_scope 2>/dev/null
    echo ""

    echo "--- Filesystem Security ---"
    sysctl fs.protected_hardlinks 2>/dev/null
    sysctl fs.protected_symlinks 2>/dev/null
    sysctl fs.suid_dumpable 2>/dev/null
    echo ""

    exit 0
}

# --- Revert to backup ---
revert_settings() {
    if [[ ! -f "$BACKUP_FILE" ]]; then
        error "No backup file found at $BACKUP_FILE"
        exit 1
    fi

    log "Reverting to backup settings..."
    cp "$BACKUP_FILE" "$SYSCTL_FILE"
    sysctl -p "$SYSCTL_FILE" >/dev/null 2>&1
    log "Settings reverted successfully"
    exit 0
}

# --- Parse Arguments ---
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            usage
            ;;
        -r|--revert)
            check_root
            revert_settings
            ;;
        -s|--show)
            show_settings
            ;;
        -n|--no-backup)
            NO_BACKUP=true
            shift
            ;;
        -q|--quiet)
            QUIET=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            usage
            ;;
    esac
done

# --- Main ---
check_root

log "Starting kernel hardening via sysctl..."

# Backup existing file if it exists
if [[ "$NO_BACKUP" == "false" && -f "$SYSCTL_FILE" ]]; then
    log "Backing up existing settings to $BACKUP_FILE"
    cp "$SYSCTL_FILE" "$BACKUP_FILE"
fi

# Create the hardening configuration
log "Writing hardening configuration to $SYSCTL_FILE"

cat > "$SYSCTL_FILE" << 'SYSCTL_EOF'
# ==============================================================================
# CCDC Kernel Hardening - Sysctl Configuration
# Generated by sysctl_harden.sh
# ==============================================================================

# ==============================================================================
# NETWORK SECURITY - IPv4
# ==============================================================================

# Disable IP forwarding (enable only on routers)
net.ipv4.ip_forward = 0

# Enable SYN cookies - protects against SYN flood attacks
net.ipv4.tcp_syncookies = 1

# Disable ICMP redirects - prevents MITM attacks
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Disable secure ICMP redirects
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0

# Enable reverse path filtering - anti-IP spoofing
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Disable source routing - prevents source-routed attacks
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0

# Log martian packets (impossible addresses)
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Ignore ICMP broadcast requests (Smurf attack mitigation)
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Ignore bogus ICMP error responses
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Increase TCP SYN backlog for better handling of connection floods
net.ipv4.tcp_max_syn_backlog = 4096

# Reduce TCP FIN timeout to free up connections faster
net.ipv4.tcp_fin_timeout = 30

# Disable TCP timestamps if not needed (reduces fingerprinting)
# net.ipv4.tcp_timestamps = 0

# Enable TCP keepalive with reasonable values
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_keepalive_intvl = 15

# ==============================================================================
# NETWORK SECURITY - IPv6
# ==============================================================================

# Disable IPv6 redirects
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Disable IPv6 source routing
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Disable IPv6 router advertisements (unless needed)
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.default.accept_ra = 0

# Disable IPv6 forwarding
net.ipv6.conf.all.forwarding = 0
net.ipv6.conf.default.forwarding = 0

# ==============================================================================
# KERNEL SECURITY
# ==============================================================================

# Enable ASLR (Address Space Layout Randomization)
# 2 = Full randomization (recommended)
kernel.randomize_va_space = 2

# Restrict access to kernel pointers in /proc
# 1 = Hide for non-root, 2 = Always hide
kernel.kptr_restrict = 2

# Restrict dmesg access to root only
kernel.dmesg_restrict = 1

# Disable magic SysRq key (prevents keyboard-based attacks)
# Set to 0 to disable, or specific value for limited functions
kernel.sysrq = 0

# Restrict ptrace to parent processes only (breaks some debuggers)
# 0 = Classic, 1 = Restricted, 2 = Admin-only, 3 = No ptrace
kernel.yama.ptrace_scope = 1

# Restrict access to perf events
kernel.perf_event_paranoid = 3

# Disable unprivileged BPF (eBPF exploits)
kernel.unprivileged_bpf_disabled = 1

# Disable user namespaces for unprivileged users (reduces attack surface)
# Comment out if containers need unprivileged user namespaces
# kernel.unprivileged_userns_clone = 0

# ==============================================================================
# FILESYSTEM SECURITY
# ==============================================================================

# Protect hardlinks - only owner can create hardlinks
fs.protected_hardlinks = 1

# Protect symlinks - only follow symlinks in sticky directories if owner matches
fs.protected_symlinks = 1

# Protect FIFOs in sticky directories
fs.protected_fifos = 2

# Protect regular files in sticky directories
fs.protected_regular = 2

# Disable core dumps for SUID programs
fs.suid_dumpable = 0

# ==============================================================================
# MEMORY SECURITY
# ==============================================================================

# Restrict mmap to higher addresses (makes exploits harder)
vm.mmap_min_addr = 65536

# Disable memory overcommit (prevents OOM situations)
# 0 = Heuristic, 1 = Always overcommit, 2 = Don't overcommit
# vm.overcommit_memory = 2

# Increase randomness for mmap base address
vm.mmap_rnd_bits = 32
vm.mmap_rnd_compat_bits = 16

# ==============================================================================
# End of CCDC Hardening Configuration
# ==============================================================================
SYSCTL_EOF

# Apply the settings
log "Applying sysctl settings..."
if sysctl -p "$SYSCTL_FILE" >/dev/null 2>&1; then
    log "Kernel hardening applied successfully"
else
    # Some settings might fail on certain kernels, apply what we can
    warn "Some settings may not be supported on this kernel"
    sysctl -p "$SYSCTL_FILE" 2>&1 | grep -v "^sysctl:" || true
fi

# Summary
echo ""
echo "=========================================="
echo "KERNEL HARDENING COMPLETE"
echo "=========================================="
echo ""
echo "Configuration file: $SYSCTL_FILE"
[[ "$NO_BACKUP" == "false" && -f "$BACKUP_FILE" ]] && echo "Backup file: $BACKUP_FILE"
echo ""
echo "Key settings applied:"
echo "  - IP forwarding disabled"
echo "  - SYN cookies enabled"
echo "  - ICMP redirects disabled"
echo "  - Reverse path filtering enabled"
echo "  - Source routing disabled"
echo "  - ASLR enabled (full)"
echo "  - Kernel pointer restriction enabled"
echo "  - dmesg restricted to root"
echo "  - Magic SysRq disabled"
echo "  - Symlink/hardlink protections enabled"
echo ""
echo "To view current settings: $0 --show"
echo "To revert changes: $0 --revert"
echo "=========================================="

exit 0
